# This file was generated by Codebase-Generator, do not edit directly

from typing import Dict, Type

from recipe_executor.steps.base import BaseStep


# A global registry mapping step type names to their implementation classes
STEP_REGISTRY: Dict[str, Type[BaseStep]] = {}
